project_id     = "ops-agnieszka-pasieka"
project_number = "45590649370"
region         = "us-west1"
input-bucket   = "input-bucket-ops-agnieszka-pasieka"
cf-bucket      = "cf-bucket-ops-agnieszka-pasieka"
user           = "agni3921@mgcp.rackspace.com"
topic          = "travel-topic-235"
function       = "gtsfunction"